title: S3 Migration Scheduler
description: Enterprise S3 Migration Made Simple
url: "https://s3migration.com"
baseurl: ""

markdown: kramdown
highlighter: rouge

collections:
  docs:
    output: true
    permalink: /:collection/:name/

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
